<a href="https://colab.research.google.com/github/Saramohamed188/DEPI/blob/main/avocado_dataset_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Avocado

In [ ]:
import pandas as pd
import numpy as np
import datetime as dt

In [ ]:
# Q1: Read your dataset, and using a dedicated pandas function view the first 5 rows
df = pd.read_csv('/content/avocado-dataset.csv', index_col = 'Unnamed: 0', parse_dates=[1], infer_datetime_format=True)
df.head()

<ipython-input-2-7abbe3880706>:2: FutureWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  df = pd.read_csv('/content/avocado-dataset.csv', index_col = 'Unnamed: 0', parse_dates=[1], infer_datetime_format=True)

,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany
2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany
3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany
4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany

In [ ]:
# Q2: gain insights of your data set and see general information about each feature and the total number of non-null values in each variable
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18249 entries, 0 to 11
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          18249 non-null  datetime64[ns]
 1   AveragePrice  18249 non-null  float64
 2   Total Volume  18249 non-null  float64
 3   4046          18249 non-null  float64
 4   4225          18249 non-null  float64
 5   4770          18249 non-null  float64
 6   Total Bags    18249 non-null  float64
 7   Small Bags    18249 non-null  float64
 8   Large Bags    18249 non-null  float64
 9   XLarge Bags   18249 non-null  float64
 10  type          18249 non-null  object
 11  year          18249 non-null  int64
 12  region        18249 non-null  object
dtypes: datetime64[ns](1), float64(9), int64(1), object(2)
memory usage: 1.9+ MB

In [ ]:
# Q3: use a dedicated pandas function that gives summary statstics for only intersting numerical features in your data set.
df.describe()

,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,year
count,18249,18249.000000,1.824900e+04,1.824900e+04,1.824900e+04,1.824900e+04,1.824900e+04,1.824900e+04,1.824900e+04,18249.000000,18249.000000
mean,2016-08-13 23:30:43.498273792,1.405978,8.506440e+05,2.930084e+05,2.951546e+05,2.283974e+04,2.396392e+05,1.821947e+05,5.433809e+04,3106.426507,2016.147899
min,2015-01-04 00:00:00,0.440000,8.456000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,2015.000000
25%,2015-10-25 00:00:00,1.100000,1.083858e+04,8.540700e+02,3.008780e+03,0.000000e+00,5.088640e+03,2.849420e+03,1.274700e+02,0.000000,2015.000000
50%,2016-08-14 00:00:00,1.370000,1.073768e+05,8.645300e+03,2.906102e+04,1.849900e+02,3.974383e+04,2.636282e+04,2.647710e+03,0.000000,2016.000000
75%,2017-06-04 00:00:00,1.660000,4.329623e+05,1.110202e+05,1.502069e+05,6.243420e+03,1.107834e+05,8.333767e+04,2.202925e+04,132.500000,2017.000000
max,2018-03-25 00:00:00,3.250000,6.250565e+07,2.274362e+07,2.047057e+07,2.546439e+06,1.937313e+07,1.338459e+07,5.719097e+06,551693.650000,2018.000000
std,NaN,0.402677,3.453545e+06,1.264989e+06,1.204120e+06,1.074641e+05,9.862424e+05,7.461785e+05,2.439660e+05,17692.894652,0.939938

In [ ]:
# Q4: Can you dedect the missleading value from the above summary statstics?
# Answer: 4046,4225,4770,Total Bags, Small Bags, Large Bags and XLarge Bags a minimum of 0 which means
# either it is an error entered or the data entry deliberately entered 0 to complete a target number of sales.

In [ ]:
df.isnull()

,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
# Q5: Let us now look at the datatypes of all these columns.
result = df.dtypes
result

Date            datetime64[ns]
AveragePrice           float64
Total Volume           float64
4046                   float64
4225                   float64
4770                   float64
Total Bags             float64
Small Bags             float64
Large Bags             float64
XLarge Bags            float64
type                    object
year                     int64
region                  object
dtype: object

In [ ]:
# Q6: Sort your data set by Date column
df.sort_values(by = 'Date')

,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
51,2015-01-04,1.75,27365.89,9307.34,3844.81,615.28,13598.46,13061.10,537.36,0.00,organic,2015,Southeast
51,2015-01-04,1.49,17723.17,1189.35,15628.27,0.00,905.55,905.55,0.00,0.00,organic,2015,Chicago
51,2015-01-04,1.68,2896.72,161.68,206.96,0.00,2528.08,2528.08,0.00,0.00,organic,2015,HarrisburgScranton
51,2015-01-04,1.52,54956.80,3013.04,35456.88,1561.70,14925.18,11264.80,3660.38,0.00,conventional,2015,Pittsburgh
51,2015-01-04,1.64,1505.12,1.27,1129.50,0.00,374.35,186.67,187.68,0.00,organic,2015,Boise
...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,2018-03-25,1.36,908202.13,142681.06,463136.28,174975.75,127409.04,103579.41,22467.04,1362.59,conventional,2018,Chicago
0,2018-03-25,0.70,9010588.32,3999735.71,966589.50,30130.82,4014132.29,3398569.92,546409.74,69152.63,conventional,2018,SouthCentral
0,2018-03-25,1.42,163496.70,29253.30,5080.04,0.00,129163.36,109052.26,20111.10,0.00,organic,2018,SouthCentral
0,2018-03-25,1.70,190257.38,29644.09,70982.10,0.00,89631.19,89424.11,207.08,0.00,organic,2018,California
0,2018-03-25,1.34,1774776.77,63905.98,908653.71,843.45,801373.63,774634.09,23833.93,2905.61,conventional,2018,NewYork

In [ ]:
# Q7: Check for unique values of all columns
df.nunique()

Date              169
AveragePrice      259
Total Volume    18237
4046            17702
4225            18103
4770            12071
Total Bags      18097
Small Bags      17321
Large Bags      15082
XLarge Bags      5588
type                2
year                4
region             54
dtype: int64

In [ ]:
df.groupby(['region', 'year'])['AveragePrice'].mean()

region            year
Albany            2015    1.538750
                  2016    1.533942
                  2017    1.637830
                  2018    1.435833
Atlanta           2015    1.380577
                            ...
West              2018    1.297083
WestTexNewMexico  2015    1.259320
                  2016    1.246635
                  2017    1.281538
                  2018    1.251250
Name: AveragePrice, Length: 216, dtype: float64

In [ ]:
# Q8: what is the average price for each region for the year 2018?
df_2018 = df[df['year'] == 2018]
df_2018.groupby('region')['AveragePrice'].mean()

region
Albany                 1.435833
Atlanta                1.288750
BaltimoreWashington    1.378333
Boise                  1.492500
Boston                 1.576667
BuffaloRochester       1.226250
California             1.411250
Charlotte              1.482500
Chicago                1.561667
CincinnatiDayton       1.275833
Columbus               1.171667
DallasFtWorth          1.102917
Denver                 1.280833
Detroit                1.177917
GrandRapids            1.328333
GreatLakes             1.278333
HarrisburgScranton     1.336667
HartfordSpringfield    1.677500
Houston                1.042083
Indianapolis           1.168333
Jacksonville           1.456667
LasVegas               1.393750
LosAngeles             1.351667
Louisville             1.267917
MiamiFtLauderdale      1.344167
Midsouth               1.358333
Nashville              1.222500
NewOrleansMobile       1.204167
NewYork                1.574583
Northeast              1.474167
NorthernNewEngland     1.421250
Orlando                1.354583
Philadelphia           1.448750
PhoenixTucson          1.155000
Pittsburgh             1.275417
Plains                 1.359583
Portland               1.396250
RaleighGreensboro      1.535000
RichmondNorfolk        1.235000
Roanoke                1.285833
Sacramento             1.472083
SanDiego               1.477917
SanFrancisco           1.549583
Seattle                1.455000
SouthCarolina          1.268333
SouthCentral           1.104583
Southeast              1.302917
Spokane                1.425000
StLouis                1.465833
Syracuse               1.250417
Tampa                  1.330833
TotalUS                1.307083
West                   1.297083
WestTexNewMexico       1.251250
Name: AveragePrice, dtype: float64

In [ ]:
# Q9 : How much was the total of average price for each year for the organic type?
df_organic = df[df['type'] == 'organic']
df_organic.groupby('year')['AveragePrice'].sum()

year
2015    4697.02
2016    4413.29
2017    4963.59
2018    1015.53
Name: AveragePrice, dtype: float64

In [ ]:
df.head()

,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany
2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany
3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany
4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany

In [ ]:
# Q10: How much was the Average price for each month of each region? To  do this you may want to create column feature, we created
      # a function for you just apply it, and in the next cell you will do the computation
df['month'] = df['Date'].dt.month
df.groupby(['region', 'month'])['AveragePrice'].mean()

region            month
Albany            1        1.538056
                  2        1.471563
                  3        1.519118
                  4        1.548846
                  5        1.580000
                             ...
WestTexNewMexico  8        1.385769
                  9        1.535417
                  10       1.631786
                  11       1.369231
                  12       1.222400
Name: AveragePrice, Length: 648, dtype: float64

In [ ]:
# Q11: now compute the total of Average price for each month of each region.
df.groupby(['region' , 'month'])['AveragePrice'].sum()

region            month
Albany            1        55.37
                  2        47.09
                  3        51.65
                  4        40.27
                  5        44.24
                           ...
WestTexNewMexico  8        36.03
                  9        36.85
                  10       45.69
                  11       35.60
                  12       30.56
Name: AveragePrice, Length: 648, dtype: float64

In [ ]:
max_x = df.loc[df['AveragePrice'].idxmax()]
max_x

,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
8,2015-11-01,1.02,99811.42,1022.15,87315.57,85.34,11388.36,11104.53,283.83,0.00,conventional,2015,Albany
8,2015-11-01,0.99,419088.74,290457.50,62980.07,252.79,65398.38,39460.77,25929.39,8.22,conventional,2015,Atlanta
8,2015-11-01,1.12,742220.67,51860.07,473819.14,58615.76,157925.70,152716.40,5209.30,0.00,conventional,2015,BaltimoreWashington
8,2015-11-01,1.14,53585.51,30434.99,4359.52,6428.27,12362.73,12331.82,0.00,30.91,conventional,2015,Boise
8,2015-11-01,1.06,553096.84,4886.14,449532.49,170.29,98507.92,93443.08,5064.84,0.00,conventional,2015,Boston
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8,2018-01-28,1.19,6393.58,30.09,128.49,0.00,6235.00,5670.94,564.06,0.00,organic,2018,Syracuse
8,2018-01-28,1.61,7695.89,156.01,859.20,0.00,6680.68,5567.39,1113.29,0.00,organic,2018,Tampa
8,2018-01-28,1.61,1336979.09,118616.17,280080.34,1270.61,936859.49,796104.27,140652.84,102.38,organic,2018,TotalUS
8,2018-01-28,1.80,185974.53,22918.40,33051.14,93.52,129911.47,77822.23,51986.86,102.38,organic,2018,West
8,2018-01-28,1.71,13888.04,1191.70,3431.50,0.00,9264.84,8940.04,324.80,0.00,organic,2018,WestTexNewMexico

In [ ]:
# Q13: Create a summary table description table reflecting each region and its total bags.
summary_stats = df.groupby('region')['Total Bags'].describe()
summary_table = summary_stats.transpose()
summary_table

region,Albany,Atlanta,BaltimoreWashington,Boise,Boston,BuffaloRochester,California,Charlotte,Chicago,CincinnatiDayton,...,SouthCarolina,SouthCentral,Southeast,Spokane,StLouis,Syracuse,Tampa,TotalUS,West,WestTexNewMexico
count,338.000000,338.000000,338.000000,338.000000,338.000000,338.000000,3.380000e+02,338.000000,338.000000,338.000000,...,338.000000,3.380000e+02,3.380000e+02,338.000000,338.000000,338.000000,338.000000,3.380000e+02,3.380000e+02,335.000000
mean,7929.747367,84498.560888,104456.053462,15974.592456,63596.085207,34351.336183,7.298290e+05,34609.297071,49897.634970,61828.161065,...,53707.614734,6.905102e+05,5.370640e+05,18504.070621,43597.724763,12403.631509,57682.520444,4.847931e+06,1.086017e+06,105362.732925
std,7417.431117,100747.121450,96552.993908,19764.085291,54306.842280,33224.540571,8.137552e+05,37032.501145,54821.368228,69183.653151,...,55020.427490,7.732275e+05,5.685711e+05,22025.909695,49147.564465,11098.505797,61710.019081,4.889033e+06,1.167126e+06,118801.443869
min,503.440000,0.000000,352.360000,7.020000,1042.300000,320.000000,4.836220e+03,280.000000,33.330000,119.000000,...,457.750000,8.418740e+03,5.214880e+03,0.000000,0.000000,356.560000,400.000000,1.198562e+05,1.456371e+04,180.000000
25%,1591.277500,4627.410000,8291.830000,1270.030000,11936.305000,4144.405000,5.390535e+04,2116.562500,2029.582500,5339.900000,...,4415.617500,7.216745e+04,3.625914e+04,1303.392500,3472.957500,2042.295000,3105.727500,4.989912e+05,9.317970e+04,7759.795000
50%,5806.785000,31405.925000,88169.375000,4460.305000,49575.640000,16212.560000,3.045142e+05,22935.705000,37888.040000,39138.230000,...,25097.125000,3.761693e+05,2.614840e+05,6406.990000,25669.220000,7200.455000,30488.180000,2.771014e+06,4.802429e+05,68482.620000
75%,12548.972500,179033.745000,191550.187500,31487.112500,112090.520000,65893.000000,1.505423e+06,62977.667500,90405.070000,111916.172500,...,99592.737500,1.308730e+06,1.013282e+06,36547.362500,70742.037500,22989.042500,103242.712500,9.578887e+06,2.246257e+06,194438.705000
max,36806.790000,425991.210000,488208.250000,93735.230000,220254.400000,101271.160000,3.462626e+06,223765.320000,510679.100000,397270.050000,...,272030.470000,4.014132e+06,2.379984e+06,89795.190000,260500.630000,35695.670000,260556.300000,1.937313e+07,4.145407e+06,424013.400000

In [ ]:
# Q14: which type crosponds for highest total Average Price?
df.groupby('type')['AveragePrice'].sum()

type
conventional    10568.27
organic         15089.43
Name: AveragePrice, dtype: float64

In [ ]:
# Q14: what is the total of average price for each region for the organic type?
df_organic.groupby('region')['AveragePrice'].sum()

region
Albany                 299.69
Atlanta                271.60
BaltimoreWashington    291.40
Boise                  273.82
Boston                 297.00
BuffaloRochester       279.08
California             284.80
Charlotte              327.35
Chicago                294.77
CincinnatiDayton       237.09
Columbus               243.24
DallasFtWorth          223.88
Denver                 230.38
Detroit                241.37
GrandRapids            284.76
GreatLakes             252.69
HarrisburgScranton     298.75
HartfordSpringfield    376.74
Houston                214.76
Indianapolis           250.65
Jacksonville           308.98
LasVegas               295.56
LosAngeles             245.99
Louisville             248.10
MiamiFtLauderdale      270.85
Midsouth               270.80
Nashville              238.51
NewOrleansMobile       257.61
NewYork                346.96
Northeast              314.24
NorthernNewEngland     286.38
Orlando                303.86
Philadelphia           315.68
PhoenixTucson          290.79
Pittsburgh             249.78
Plains                 288.57
Portland               268.53
RaleighGreensboro      318.25
RichmondNorfolk        247.22
Roanoke                236.57
Sacramento             332.79
SanDiego               293.19
SanFrancisco           373.70
Seattle                289.90
SouthCarolina          280.60
SouthCentral           225.29
Southeast              275.98
Spokane                300.01
StLouis                283.16
Syracuse               279.48
Tampa                  273.12
TotalUS                261.28
West                   263.53
WestTexNewMexico       280.35
Name: AveragePrice, dtype: float64

In [ ]:
# Q15: creat a pivot table showing total of Average price for each month indexed by year.
df.pivot_table(index = 'year', columns = 'type', values = 'AveragePrice', aggfunc = 'sum')

month,1,2,3,4,5,6,7,8,9,10,11,12
year,,,,,,,,,,,,
2015,589.70,573.24,735.47,597.65,726.13,604.40,608.88,780.02,626.03,601.33,718.53,562.56
2016,669.70,534.43,528.86,520.57,647.85,554.28,756.72,609.60,616.84,840.83,669.61,568.51
2017,689.85,524.79,604.34,811.41,662.08,664.52,845.06,733.95,795.29,946.32,655.47,736.48
2018,599.37,569.68,577.35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Q16: creat a pivot table showing total of Average price for each month indexed by year and type.
df.pivot_table(index = 'year', columns = 'month', values = 'AveragePrice', aggfunc = 'sum')

type  conventional  organic
year
2015       3026.92  4697.02
2016       3104.51  4413.29
2017       3705.97  4963.59
2018        730.87  1015.53

In [ ]:
df.head()

,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region,month
0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany,12
1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany,12
2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany,12
3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany,12
4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany,11

In [ ]:
# Q17: Correlation between 'Total Volume','Total Bags' and 'AveragePrice'.
df[['Total Volume', 'Total Bags']].corr()

              Total Volume  Total Bags
Total Volume      1.000000    0.963047
Total Bags        0.963047    1.000000

In [ ]:
# Q18: drop the 'Small Bags' feature.
df_dropped = df.drop('Small Bags', axis = 1)
df_dropped.head()

,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Large Bags,XLarge Bags,type,year,region,month
0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,93.25,0.0,conventional,2015,Albany,12
1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,97.49,0.0,conventional,2015,Albany,12
2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,103.14,0.0,conventional,2015,Albany,12
3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,133.76,0.0,conventional,2015,Albany,12
4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,197.69,0.0,conventional,2015,Albany,11

In [ ]:
# Q19: save your data set with .csv format for later use.
# df_dropped.to_csv('Avocado_with_features.csv', index = False)

In [ ]:
# Q20: write the conclusion you came up with after your analysis, including your recommendations for the mangment to
#  improve the renting bikes business.

In [ ]:
# Q21: if you were in charge to gather more data to help you better tackle down the problem, what features you might need?